### PR TITLE
fix: example messages

### LINKED ISSUE #2: Example message exchange does not work.
When running the example client and server, the `TestMessage` exchange does not work. It seems as though the client and server need the same type of message, otherwise you get the following error:

```
Message Error: callback type not registered: component type not found for ID 7783821856285832660
```

### PR DESCRIPTION
**Pull request by mikeder**
Use a shared message type to prevent `Message Error: callback type not registered: component type not found for ID 7783821856285832660` errors in example.

Resolves: #2

### CODE REVIEW

File: examples/shared/message.go [hunk 1]
```diff
@@ -0,0 +1,9 @@
+package shared
+
+import "github.com/yohamta/donburi"
+
+type TestMessage struct {
+	Message string
+}
+
+var TestMessageComponent = donburi.NewComponentType[TestMessage]()
```
Comment (mikeder) [inline examples/shared/message.go]: Not sure if this is actually required, I think just using the same `TestMessage` type is sufficient.

Comment (imthatgin) [reply examples/shared/message.go]: Yeah just use the same actual type. There's a bit of code that generates a hash for the type name, so as long as they match it should work.
